### ISSUE TITLE
[멀티 모듈 적용 후 CI/CD]

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#25]
# 멀티모듈 적용 후 CI/CD 파이프라인의 수정이 필요
## 1. 최초 deploy.sh 파일과 appsec.yml 파일 모두 수정 - 오류 발생
- deploy.sh 파일에서 hobbyloop-admin 어플리케이션과 hobbyloop-api 어플리케이션을 배포할 수 있도록 스트립트 개선
- appspec.yml 파일 또한 수정(자동 배포 실패 원인 - 현재는 해결)
---
### As is(deploy.sh)
```
PROJECT_NAME="hobbyloop"
JAR_PATH="/home/ubuntu/hobbyloop/build/libs/hobbyloop-0.0.1-SNAPSHOT.jar"
DEPLOY_PATH=/home/ubuntu/$PROJECT_NAME/
DEPLOY_LOG_PATH="/home/ubuntu/$PROJECT_NAME/deploy.log"
DEPLOY_ERR_LOG_PATH="/home/ubuntu/$PROJECT_NAME/deploy_err.log"
APPLICATION_LOG_PATH="/home/ubuntu/$PROJECT_NAME/application.log"
BUILD_JAR=$(ls $JAR_PATH)
JAR_NAME=$(basename $BUILD_JAR)

echo "===== 배포 시작 (시간) : $(date +%c) =====" >> $DEPLOY_LOG_PATH

echo "> build 파일명: $JAR_NAME" >> $DEPLOY_LOG_PATH
echo "> build 파일 복사" >> $DEPLOY_LOG_PATH
cp $BUILD_JAR $DEPLOY_PATH

echo "> 현재 동작중인 어플리케이션 pid 체크" >> $DEPLOY_LOG_PATH
CURRENT_PID=$(pgrep -f $JAR_NAME)

if [ -z $CURRENT_PID ]
then
  echo "> 현재 동작중인 어플리케이션 존재 X" >> $DEPLOY_LOG_PATH
else
  echo "> 현재 동작중인 어플리케이션 존재 O" >> $DEPLOY_LOG_PATH
  echo "> 현재 동작중인 어플리케이션 강제 종료 진행" >> $DEPLOY_LOG_PATH
  echo "> kill -9 $CURRENT_PID" >> $DEPLOY_LOG_PATH
  kill -9 $CURRENT_PID
fi

DEPLOY_JAR=$DEPLOY_PATH$JAR_NAME
echo "> DEPLOY_JAR 배포" >> $DEPLOY_LOG_PATH
nohup java -jar $DEPLOY_JAR >> $APPLICATION_LOG_PATH 2> $DEPLOY_ERR_LOG_PATH &

sleep 3

echo "> 배포 종료 : $(date +%c)" >> $DEPLOY_LOG_PATH
```
### As is(appspec.yml)
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hobbyloop
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu

```
--- 
### To be(deploy.sh)
```
#!/bin/bash
API_PROJECT_NAME="hobbyloop-api"

# hobbyloop-api deploy

API_JAR_PATH="/home/ubuntu/hobbyloop/$API_PROJECT_NAME/build/libs/hobbyloop-api-0.0.1-SNAPSHOT.jar"
API_DEPLOY_PATH="/home/ubuntu/hobbyloop/$API_PROJECT_NAME/"
API_DEPLOY_LOG_PATH="/home/ubuntu/hobbyloop/$API_PROJECT_NAME/deploy.log"
API_DEPLOY_ERR_LOG_PATH="/home/ubuntu/hobbyloop/$API_PROJECT_NAME/deploy_err.log"
API_APPLICATION_LOG_PATH="/home/ubuntu/hobbyloop/$API_PROJECT_NAME/application.log"
API_BUILD_JAR=$(ls $API_JAR_PATH)
API_JAR_NAME=$(basename $API_BUILD_JAR)

ADMIN_PROJECT_NAME="hobbyloop-admin"
# hobbyloop-admin deploy
ADMIN_JAR_PATH="/home/ubuntu/hobbyloop/$ADMIN_PROJECT_NAME/build/libs/hobbyloop-admin-0.0.1-SNAPSHOT.jar"
ADMIN_DEPLOY_PATH="/home/ubuntu/hobbyloop/$ADMIN_PROJECT_NAME/"
ADMIN_DEPLOY_LOG_PATH="/home/ubuntu/hobbyloop/$ADMIN_PROJECT_NAME/deploy.log"
ADMIN_DEPLOY_ERR_LOG_PATH="/home/ubuntu/hobbyloop/$ADMIN_PROJECT_NAME/deploy_err.log"
ADMIN_APPLICATION_LOG_PATH="/home/ubuntu/hobbyloop/$ADMIN_PROJECT_NAME/application.log"
ADMIN_BUILD_JAR=$(ls $ADMIN_JAR_PATH)
ADMIN_JAR_NAME=$(basename $ADMIN_BUILD_JAR)

echo "===== 배포 시작 (시간) : $(date +%c) =====" >> $API_DEPLOY_LOG_PATH
echo "===== 배포 시작 (시간) : $(date +%c) =====" >> $ADMIN_DEPLOY_LOG_PATH

# hobbyloop-api 배포 시작
echo "> build 파일명: $API_JAR_NAME" >> $API_DEPLOY_LOG_PATH
echo "> build 파일 복사" >> $API_DEPLOY_LOG_PATH
cp $API_BUILD_JAR $API_DEPLOY_PATH

echo "> 현재 동작중인 어플리케이션 pid 체크" >> $API_DEPLOY_LOG_PATH
CURRENT_PID=$(pgrep -f $API_JAR_NAME)

if [ -z $CURRENT_PID ]
then
  echo "> 현재 동작중인 어플리케이션 존재 X" >> $API_DEPLOY_LOG_PATH
else
  echo "> 현재 동작중인 어플리케이션 존재 O" >> $API_DEPLOY_LOG_PATH
  echo "> 현재 동작중인 어플리케이션 강제 종료 진행" >> $API_DEPLOY_LOG_PATH
  echo "> kill -9 $CURRENT_PID" >> $API_DEPLOY_LOG_PATH
  kill -9 $CURRENT_PID
fi

DEPLOY_API_JAR=$API_DEPLOY_PATH$API_JAR_NAME
echo "> DEPLOY_JAR 배포" >> $API_DEPLOY_LOG_PATH
nohup java -jar $DEPLOY_API_JAR>> $API_APPLICATION_LOG_PATH 2> $API_DEPLOY_ERR_LOG_PATH &

sleep 3

echo "> 배포 종료 : $(date +%c)" >> $API_DEPLOY_LOG_PATH

# hobbyloop-admin 배포 시작
echo "> build 파일명: $ADMIN_JAR_NAME" >> $ADMIN_DEPLOY_LOG_PATH
echo "> build 파일 복사" >> $ADMIN_DEPLOY_LOG_PATH
cp $ADMIN_BUILD_JAR $ADMIN_DEPLOY_PATH

echo "> 현재 동작중인 어플리케이션 pid 체크" >> $ADMIN_DEPLOY_LOG_PATH
CURRENT_PID=$(pgrep -f $ADMIN_JAR_NAME)

if [ -z $CURRENT_PID ]
then
  echo "> 현재 동작중인 어플리케이션 존재 X" >> $ADMIN_DEPLOY_LOG_PATH
else
  echo "> 현재 동작중인 어플리케이션 존재 O" >> $ADMIN_DEPLOY_LOG_PATH
  echo "> 현재 동작중인 어플리케이션 강제 종료 진행" >> $ADMIN_DEPLOY_LOG_PATH
  echo "> kill -9 $CURRENT_PID" >> $ADMIN_DEPLOY_LOG_PATH
  kill -9 $CURRENT_PID
fi

DEPLOY_ADMIN_JAR=$ADMIN_DEPLOY_PATH$ADMIN_JAR_NAME
echo "> DEPLOY_JAR 배포" >> $ADMIN_DEPLOY_LOG_PATH
nohup java -jar $DEPLOY_ADMIN_JAR>> $ADMIN_APPLICATION_LOG_PATH 2> $ADMIN_DEPLOY_ERR_LOG_PATH &

sleep 3

echo "> 배포 종료 : $(date +%c)" >> $ADMIN_DEPLOY_LOG_PATH
```
### To be(appspec.yml)
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hobbyloop/hobbyloop-api
    overwrite: yes
  - source: /
    destination: /home/ubuntu/hobbyloop/hobbyloop-admin
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu

```
---
- 이때 /home/ubuntu/hobbyloop 내에 /hobbyloop-api , /hobbyloop-admin 디렉토리가 생성됨
- 두 개의 디렉토리 내부에는 hobbyloop 프로젝트 전체가 빌드되어 있었음
- 최초 문제 발견 시 deploy.sh 파일에서 deploy script 가 잘못되었다고 판단하여 계속해서 수정

## 2. deploy script 를 모듈별로 나눠도 보고 여러 방법을 시도했지만 자동 배포 환경 구축 실패
- workflow 수정 시작
- workflow 내에서 deploy.sh 파일을 최상위 디렉토리에 위치시키기 위한 시도를 했지만 그럼에도 실패
- 아직도 두 개의 디렉토리(/hobbyloop-api, /hobbyloop-admin)에 프로젝트가 각각 하나씩 생성됨

--- 
## 3. 최종적으로 appspec 파일 수정
- 결국 deploy script 와 workflow 를 수정해도 해결되지 않아 appspec 파일을 살펴봄
- overwrite : yes 라는 부분에 대해서 생각해보다 문제 파악
- source 파일이 두개가 생성이 되는 문제였음 -> hobbyloop-api 에 하나, hobbyloop-admin에 하나
---
- 이로 인해 전체적인 디렉토리 구조가 깨져버렸고, deploy.sh 파일에서 정의한 디렉토리 구조와 상이한 문제를 발생시켜서 자동 배포를 실패했던 것
### As is(appspec.yml)
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hobbyloop/hobbyloop-api
    overwrite: yes
  - source: /
    destination: /home/ubuntu/hobbyloop/hobbyloop-admin
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
```

### To be(appspec.yml)
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/hobbyloop
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu

```
- 위와 같이 appspec.yml 파일 수정 후 자동 배포 환경 구축 완료
