### ISSUE TITLE
[CI/CD] pr 트리거시의 github action workflow 수정

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#30]
# 1. 기존 workflow 에서 pull request 생성과 merge 두 번의 시점에서 동일한 작업 실행
---
- pr 시에 배포 1회, merge 시에 배포 1회 실행
- pr 시에는 빌드만 실시하여 코드 검토
- 이후 merge 시에는 배포를 하도록 변경

# 2. 코드 변경
- pr 시에 동작하는 workflow 를 하나 더 정의하고 기존의 workflow 에서는 pr trigger 를 제거

## As is
name: Java CI with Gradle

```
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
```

## To be
```
name: CI/CD in Push trigger

on:
  push:
    branches: [ "develop" ]
```

```
name: Build in Pull Request trigger

on:
  pull_request:
    branches: [ "develop" ]
```
